spring:
  application:
    name: webBH



  # Config JDBC
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: root
    password: 1234
    driverClassName: org.postgresql.Driver

  #    Config JPA
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+7
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true



  # Config Swagger
  springdoc:
    swagger-ui:
      parth: webanhang.html
      operation-sorter: method